# 無効にするルール。
disabled_rules:
 - force_cast # 場合によっては使用するため
 - colon # コロン位置を揃えたい
 - comma # カンマ位置を揃えたい
 - identifier_name # 変数名にアンスコ使いたい
 - switch_case_on_newline # 一行で書いたほうが簡潔な場合もある
 - implicit_getter # IBInspectableで使用するため
 - valid_ibinspectable # IBInspectableをComputed Propertyで使いたいことがあるため
 - nesting #テスト等でメソッド内で型定義したいパターンがあるため
  
# デフォルト無効のルールのうち、有効にするもの。
opt_in_rules:
 - closure_spacing # クロージャのカッコの近くにスペース強制
 - empty_count # == 0 のかわりにisEmpty
 - explicit_init # init()使わない
 - first_where # .filter { }.firstよりも.first(where:)を用いる
 - object_literal # #imageLiteralや#colorLiteralを用いる
 - private_outlet # outletはprivateにする
 - prohibited_super_call # いくつかのメソッドにおいてはsuperを呼び出すべきではない
 - redundant_nil_coalescing # nil結合演算子において，左辺がnilの場合のみ評価される性質上，右辺にnilを書くのは冗長なため，書くべきでない
 
excluded:
 # 追加したOSSライブラリは対象に含めたくない
 - Carthage/
 # 自動生成したリソースファイルは対象に含めない
 - Presentation/Resource/Generated
# 1行あたりの文字数制限を300に変更
# プロジェクト作成時にデフォルトで追加されるコメントをひっかけないため
line_length: 300
