name: Pokedex
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      CURRENT_PROJECT_VERSION: 1
    dependencies:
      - carthage: Alamofire
