name: Pokedex
options:
  deploymentTarget:
    iOS: 11.0
packages:
    Alamofire:
      url: https://github.com/Alamofire/Alamofire.git
      version: 5.2.2
    Nuke:
      url: https://github.com/kean/Nuke.git
      version: 9.1.2
settings:
  DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES #Read: https://forums.swift.org/t/adding-a-package-to-two-targets-in-one-projects-results-in-an-error/35007
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedex
      CODE_SIGN_STYLE: Automatic
    dependencies:
    - target: DataStore
    - target: Domain
    - target: Presentation
    - target: QuizTodayExtension
      codeSign: false
      embed: true
    postbuildScripts:
          - script: |
              if which mint >/dev/null; then
                mint run swiftlint swiftlint autocorrect --format
                mint run swiftlint swiftlint
              else
                echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
              fi
            name: Run SwiftLint
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.DataStore
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Alamofire
      - package: Nuke
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Presentation
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - package: Nuke
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Domain
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
  QuizTodayExtension:
    type: app-extension
    platform: iOS
    sources: [QuizTodayExtension]
    settings:
      PRODUCT_NAME: Who is That Pokémon?
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.QuizTodayExtension
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - package: Nuke
      - sdk: NotificationCenter.framework
  PokedexTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PokedexTests
    settings:
      base:
        INFOPLIST_FILE: PokedexTests/Info.plist
    dependencies:
      - target: Pokedex
