name: Pokedex
options:
  deploymentTarget:
    iOS: 11.0
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedex
    dependencies:
    - target: API
    - target: Presentation
  API:
    type: framework
    platform: iOS
    sources: [API]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.API
    dependencies:
      - carthage: Alamofire
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Presentation
    
