name: Pokedex
configs:
  Debug: debug
  Adhoc: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Adhoc: Configs/Adhoc.xcconfig
  Release: Configs/Release.xcconfig
options:
  defaultConfig: Debug
  deploymentTarget:
    iOS: 13.0
settingGroups:
  MainSettings:
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Manual
    SWIFT_VERSION: 5.0
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES #Read: https://forums.swift.org/t/adding-a-package-to-two-targets-in-one-projects-results-in-an-error/35007
packages:
    Alamofire:
      url: https://github.com/Alamofire/Alamofire.git
      version: 5.2.2
    Nuke:
      url: https://github.com/kean/Nuke.git
      version: 9.1.2
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      groups: [MainSettings]
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex.Debug
          DEBUG_INFORMATION_FORMAT: dwarf
        Adhoc:
          CODE_SIGN_IDENTITY: Apple Distribution
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex.Adhoc
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          CODE_SIGN_IDENTITY: Apple Distribution
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
    - target: DataStore
    - target: Domain
    - target: Presentation
    - target: QuizTodayExtension
      codeSign: false
      embed: true
    postbuildScripts:
      - script: |
          if which mint >/dev/null; then
            mint run swiftlint swiftlint autocorrect --format
            mint run swiftlint swiftlint
          else
            echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
        name: Run SwiftLint
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.DataStore
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Alamofire
      - package: Nuke
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.Presentation
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - package: Nuke
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.Domain
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
  QuizTodayExtension:
    type: app-extension
    platform: iOS
    sources: [QuizTodayExtension]
    settings:
      PRODUCT_NAME: Who is That Pokémon?
      CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.Debug.QuizTodayExtension
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex.QuizTodayExtension.Debug
        Adhoc:
          CODE_SIGN_IDENTITY: Apple Distribution
          PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.Adhoc.QuizTodayExtension
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex.QuizTodayExtension.Adhoc
        Release:
          CODE_SIGN_IDENTITY: Apple Distribution
          PRODUCT_BUNDLE_IDENTIFIER: TomosukeOkada.Pokedex.QuizTodayExtension
          DEVELOPMENT_TEAM: NG4PAUE398
          PROVISIONING_PROFILE_SPECIFIER: Pokedex.QuizTodayExtension
    dependencies:
      - target: Domain
      - package: Nuke
      - sdk: NotificationCenter.framework
  PokedexTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PokedexTests
    settings:
      base:
        INFOPLIST_FILE: PokedexTests/Info.plist
    dependencies:
      - target: Pokedex
schemes:
  Pokedex:
    build:
      targets:
        Pokedex: all
        PokedexTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PokedexTests
      gatherCoverageData: true
      coverageTargets:
        - Domain
        - DataStore
        - Presentation
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
