name: Pokedex
options:
  deploymentTarget:
    iOS: 11.0
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedex
      CODE_SIGN_STYLE: Automatic
    dependencies:
    - target: API
    - target: Presentation
    - carthage: Alamofire
  API:
    type: framework
    platform: iOS
    sources: [API]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.API
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - carthage: Alamofire
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Presentation
      CODE_SIGN_STYLE: Automatic
    
