name: Pokedex
options:
  deploymentTarget:
    iOS: 11.0
fileGroups:
targets:
  Pokedex:
    type: application
    platform: iOS
    sources: [Pokedex]
    settings:
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: pokedex
      CODE_SIGN_STYLE: Automatic
    dependencies:
    - target: DataStore
    - target: Domain
    - target: Presentation
    - target: Entity
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.DataStore
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - carthage: Alamofire
      - carthage: Realm
      - carthage: RealmSwift
      - target: Entity
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Presentation
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
      - target: Domain
      - target: Entity
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Domain
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
      - target: Entity
  Entity:
    type: framework
    platform: iOS
    sources: [Entity]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: pokedex.Entity
      CODE_SIGN_STYLE: Automatic
